### ISSUE TITLE
Batchnorm and data augmentation with Delta UQ

### ISSUE THREAD

**Issue by ThyrixYang** [LLNL/DeltaUQ#1]
Hi, I'm really impressed by your insightful work. 

I have a few questions:

1. Although networks with ReLU activations are not shift-invariant, I think deep networks with BatchNrom or LayerNorm are nearly shift-invariant. The Resnet used in your experiments also uses BatchNorm, which seems not consistent with your theoretical analysis, would you please explain this?
2. Since the model is trained to learn with multiple anchors, the training complexity seems to be similar to Deep-ensemble, which is much higher than normal training. Have you conducted an experimental analysis of the training cost?
3. The anchor training method seems to be similar to data augmentation methods such as mix-up, does this mean a combination of strong augmentation and ensemble will lead to better results?

**Comment by rushilanirudh** [comment]
Hi, thanks for your questions and interest. 

### Shift invariance and BN
Note, our main formulation for deltaUQ is the [c, c-x], which is a trivial transformation of the input space to a higher dimensional anchor/residual space, in this formulation shift invariance is no longer valid as the anchors are also part of the input and change at random. 

In our theoretical analysis, we connect this transformation to a simple shifted domain which we are able to analyze more rigorously using the neural tangent kernel (NTK) and show that indeed just by shifting domains by a fixed constant one can produce epistemic uncertainties. Here, using BN might cause a collapse as you suggest, but this is not our formulation, we only use it to explain how uncertainties might arise. We show that these two formulations are closely related in the NTK perturbation to further justify our result.  In the deltaUQ formulation the shifts are random and several, and as a result the “shift invariance” from BN may not apply. (It does in the trivial shift case) — because of this, even when we use BN and deltaUQ we are able to produce uncertainties. 

### Anchor corruption during training
However, we did observe that when using large networks like ResNets, the uncertainties tended to be smaller and collapse on occasion. To avoid this, during training, we introduce a simple corruption in the anchoring process as a way to prevent collapse — here we do the anchoring as [c’, c-x], where c' = F(c), for some corruption function ‘F’ (Defined [here](https://github.com/LLNL/DeltaUQ/blob/11af26d3a14fef090d88971f5455c9640297cb10/lib/deltaUQ.py#L123)). This often helped improve the quality of uncertainties.

### Training is always with a single anchor
we randomly choose an anchor for each sample in every batch. In expectation, this has the effect of combining every sample with multiple anchors (approx. = n_epochs), so in terms of training cost its always like training a single model. However, the inference cost is similar to DE, as we get multiple predictions for each sample and compute the mean and std. dev; although with only ever storing a single network. 

### Anchoring & Augmentations
Your observation is right, anchoring is similar to data augmentations except that it is a trivial augmentation where the original sample can be perfectly recovered or almost perfectly recovered by combining the anchor + delta. Using augmentations should further improve uncertainties in some situations as they also introduce aleatoric component, whereas DeltaUQ only captures epistemic uncertainties. 

You may also be interested in a different perspective on anchoring in another recently published work here https://openreview.net/forum?id=lid14UkLPd4  🙂

**Comment by ThyrixYang** [comment]
@rushilanirudh I sincerely appreciate your thorough explanation. Thank you once again for your enlightening work.
